name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    # prevent this action from running on forks
    if: github.repository == 'adrianusler/massaction'
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install uv
        uv pip install pytest
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        uv pip install -e . --system
    - name: Test with pytest
      run: |
        pytest
